# Preparing data

In [69]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df_aapl = pd.read_csv("../data/raw/yfinance_data/Data/AAPL.csv")
df_amzn = pd.read_csv("../data/raw/yfinance_data/Data/AMZN.csv")
df_goog = pd.read_csv("../data/raw/yfinance_data/Data/GOOG.csv")
df_meta = pd.read_csv("../data/raw/yfinance_data/Data/META.csv")
df_nvda = pd.read_csv("../data/raw/yfinance_data/Data/NVDA.csv")

print("AAPL")
display(df_aapl.head())

print("AMZN")
display(df_amzn.head())

print("GOOG")
display(df_goog.head())

print("META")
display(df_meta.head())

print("NVDA")
display(df_nvda.head())

AAPL

         Date     Close      High       Low      Open      Volume
0  2009-01-02  2.721686  2.730385  2.554037  2.575630   746015200
1  2009-01-05  2.836553  2.884539  2.780469  2.794266  1181608400
2  2009-01-06  2.789767  2.914229  2.770872  2.877641  1289310400
3  2009-01-07  2.729484  2.774170  2.706990  2.753477   753048800
4  2009-01-08  2.780169  2.793666  2.700393  2.712090   673500800

AMZN

         Date  Close    High     Low    Open     Volume
0  2009-01-02  2.718  2.7265  2.5535  2.5675  145928000
1  2009-01-05  2.703  2.7870  2.6515  2.7865  190196000
2  2009-01-06  2.868  2.9110  2.6875  2.7275  221602000
3  2009-01-07  2.810  2.8475  2.7675  2.8145  158854000
4  2009-01-08  2.858  2.8660  2.7290  2.7495  131558000

GOOG

         Date     Close      High       Low      Open     Volume
0  2009-01-02  7.948608  7.960977  7.557264  7.633949  144961322
1  2009-01-05  8.115089  8.194003  7.792268  7.940692  196293007
2  2009-01-06  8.263762  8.430492  8.074027  8.237046  257971329
3  2009-01-07  7.965677  8.185839  7.885034  8.121770  180453860
4  2009-01-08  8.044340  8.044340  7.850152  7.873406  144567852

META

         Date      Close       High        Low       Open     Volume
0  2012-05-18  37.995762  44.724282  37.767172  41.792356  573576400
1  2012-05-21  33.821495  36.435382  32.797807  36.306177  168192700
2  2012-05-22  30.810066  33.384198  30.750434  32.410203  101786600
3  2012-05-23  31.803938  32.300874  31.167860  31.177799   73600000
4  2012-05-24  32.827625  33.006523  31.575347  32.748117   50237200

NVDA

         Date     Close      High       Low      Open      Volume
0  2009-01-02  0.199652  0.201027  0.184294  0.184982   497124000
1  2009-01-05  0.203319  0.207904  0.195984  0.197360   705736000
2  2009-01-06  0.210196  0.216156  0.204695  0.209279   657904000
3  2009-01-07  0.197589  0.205382  0.190483  0.205382   870096000
4  2009-01-08  0.192546  0.195067  0.180626  0.195067  1014496000

In [70]:
print("AAPL")
df_aapl.info()

print("\nAMZN")
df_amzn.info()

print("\nGOOG")
df_goog.info()

print("\nMETA")
df_meta.info()

print("\nNVDA")
df_nvda.info()

AAPL
<class 'pandas.DataFrame'>
RangeIndex: 3774 entries, 0 to 3773
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    3774 non-null   str
 1   Close   3774 non-null   float64
 2   High    3774 non-null   float64
 3   Low     3774 non-null   float64
 4   Open    3774 non-null   float64
 5   Volume  3774 non-null   int64
dtypes: float64(4), int64(1), str(1)
memory usage: 177.0 KB

AMZN
<class 'pandas.DataFrame'>
RangeIndex: 3774 entries, 0 to 3773
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    3774 non-null   str
 1   Close   3774 non-null   float64
 2   High    3774 non-null   float64
 3   Low     3774 non-null   float64
 4   Open    3774 non-null   float64
 5   Volume  3774 non-null   int64
dtypes: float64(4), int64(1), str(1)
memory usage: 177.0 KB

GOOG
<class 'pandas.DataFrame'>
RangeIndex: 3774 entries, 0 to 3773
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    3774 non-null   str
 1   Close   3774 non-null   float64
 2   High    3774 non-null   float64
 3   Low     3774 non-null   float64
 4   Open    3774 non-null   float64
 5   Volume  3774 non-null   int64
dtypes: float64(4), int64(1), str(1)
memory usage: 177.0 KB

META
<class 'pandas.DataFrame'>
RangeIndex: 2923 entries, 0 to 2922
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    2923 non-null   str
 1   Close   2923 non-null   float64
 2   High    2923 non-null   float64
 3   Low     2923 non-null   float64
 4   Open    2923 non-null   float64
 5   Volume  2923 non-null   int64
dtypes: float64(4), int64(1), str(1)
memory usage: 137.1 KB

NVDA
<class 'pandas.DataFrame'>
RangeIndex: 3774 entries, 0 to 3773
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    3774 non-null   str
 1   Close   3774 non-null   float64
 2   High    3774 non-null   float64
 3   Low     3774 non-null   float64
 4   Open    3774 non-null   float64
 5   Volume  3774 non-null   int64
dtypes: float64(4), int64(1), str(1)
memory usage: 177.0 KB

In [71]:
print("AAPL")
print(df_aapl.isna().sum())

print("\nAMZN")
print(df_amzn.isna().sum())

print("\nGOOG")
print(df_goog.isna().sum())

print("\nMETA")
print(df_meta.isna().sum())

print("\nNVDA")
print(df_nvda.isna().sum())

AAPL
Date      0
Close     0
High      0
Low       0
Open      0
Volume    0
dtype: int64

AMZN
Date      0
Close     0
High      0
Low       0
Open      0
Volume    0
dtype: int64

GOOG
Date      0
Close     0
High      0
Low       0
Open      0
Volume    0
dtype: int64

META
Date      0
Close     0
High      0
Low       0
Open      0
Volume    0
dtype: int64

NVDA
Date      0
Close     0
High      0
Low       0
Open      0
Volume    0
dtype: int64

No missing values were found in any of the datasets, and all columns contain data in the correct format. So no cleaning is needed.